### ISSUE TITLE
Error: The number of tree tips in tr is not equal to the number of species in the data filter associated with the tree

### ISSUE THREAD

**Issue by siriusb-nox** [faircloth-lab/tapir#11]
Hi there,

After a couple of rather large datasets successfully analyzed, I am encountering a new issue with tapir.  I am trying to analyze a set of 143 genes, and I made sure that all my terminals in my tree (10 tips) are present in all alignments. When I execute tapir in such dataset, I get the following error message:

Estimating site rates and PI for files:
.........................Traceback (most recent call last):
  File "/home/XXX/Software/tapir/bin/tapir_compute.py", line 180, in <module>
    main()
  File "/home/XXX/Software/tapir/bin/tapir_compute.py", line 164, in main
    pis = pool.map(worker, params)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 558, in get
    raise self._value
.Exception: hyphy error: Error:
**The number of tree tips in tr (10) is not equal to the number of species in the data filter associated with the tree (8).**

Function call stack
1 : Construct the following likelihood function:nucData ; tr ; pi ;

Do you know which is the "data filter" the error message is pointing out? Is there any flag that can control such data filter threshold?

Many thanks for your help!

Best,

Oscar

**Comment by esamacas** [comment]
Hi Oscar..did you find a solution for this??.. I'm currently having the same problem..

Thanks
