### ISSUE TITLE
Test suite fails on DendroPy >= 4. 

### ISSUE THREAD

**Issue by Woods26** [faircloth-lab/tapir#7]
DendroPy 3.12.3 (June 04, 2015) passes tests.

Trace:
........tapir/compute.py:102: CriticalDeprecationWarning: Deprecated since DendroPy 4: 'vectors()' will no longer be supported in future releases; use 'sequences()' instead
  for cells in taxa.vectors():
.......E.

======================================================================
ERROR: test_dendropy_tree_adjustment (tapir.tests.test_compute.TestTreeAdjustment)

----------------------------------------------------------------------
Traceback (most recent call last):
  File "tapir/tests/test_compute.py", line 80, in setUp
    dendropy.Tree.get_from_string('(danRer6:1.74,(oryLat2:1,(gasAcu1:0.93,(fr2:0.37,tetNig2:0.37):0.56):0.07):0.74)', schema='newick')
  File "/data0/opt/anaconda2/envs/tapir/lib/python2.7/site-packages/dendropy/datamodel/basemodel.py", line 246, in get_from_string
    **kwargs)
  File "/data0/opt/anaconda2/envs/tapir/lib/python2.7/site-packages/dendropy/datamodel/treemodel.py", line 2635, in _parse_and_create_from_stream
    global_annotations_target=None)
  File "/data0/opt/anaconda2/envs/tapir/lib/python2.7/site-packages/dendropy/dataio/ioservice.py", line 362, in read_tree_lists
    global_annotations_target=global_annotations_target)
  File "/data0/opt/anaconda2/envs/tapir/lib/python2.7/site-packages/dendropy/dataio/newickreader.py", line 314, in _read
    tree_factory=tree_factory):
  File "/data0/opt/anaconda2/envs/tapir/lib/python2.7/site-packages/dendropy/dataio/newickreader.py", line 293, in tree_iter
    taxon_symbol_map_fn=taxon_symbol_mapper.require_taxon_for_symbol)
  File "/data0/opt/anaconda2/envs/tapir/lib/python2.7/site-packages/dendropy/dataio/newickreader.py", line 374, in _parse_tree_statement
    is_internal_node=None)
  File "/data0/opt/anaconda2/envs/tapir/lib/python2.7/site-packages/dendropy/dataio/newickreader.py", line 531, in _parse_tree_node_description
    nexus_tokenizer.require_next_token()
  File "/data0/opt/anaconda2/envs/tapir/lib/python2.7/site-packages/dendropy/dataio/tokenizer.py", line 159, in require_next_token
    raise exc
UnexpectedEndOfStreamError: Error parsing data source on line 1 at column 80: Unexpected end of stream

**Comment by jonchang** [comment]
Fixed in commit b610ef77.
